### ISSUE TITLE
Error opening Groot page in Firefox - plausible is not defined

### ISSUE THREAD

**Issue by OPerepadia** [BehaviorTree/btcpp_website#10]
Hello. Opening [this page](https://www.behaviortree.dev/groot/) in firefox results in the following error:

![image](https://user-images.githubusercontent.com/80095612/206188504-abcbf47c-dc37-4a37-ab94-33d0d7c58c9f.png)

I can reproduce this with Firefox 107.0.1 on Linux, and firefox 107.1.0 on Android.

UPDATE: it seems related to uBlock Origin extension. if I disable it, the page loads correctly.

**Comment by facontidavide** [comment]
thanks for reporting! Should be fixed now
