### ISSUE TITLE
Request tutorial on how to debug BT 3.8 with Groot

### ISSUE THREAD

**Issue by Lecrapouille** [BehaviorTree/btcpp_website#27]
Hi, as a newbie I could not figure out what code to add inside the C++ code of tutorial_01_first_tree (version 3.8) to communicate with Groot1 to make it show states. Sad to have to ask to chatGPT how to do it (sorry if this information exist and I have not found maybe this is not enough hightlighted):

```
#include <behaviortree_cpp_v3/loggers/bt_groot_logger.h>

BT::StdCoutLogger logger_cout(tree);
BT::MinitraceLogger logger_minitrace(tree, "minitrace.json");
BT::FileLogger logger_file(tree, "bt_trace.fbl");
BT::GrootLogger logger_groot(tree);

while (tree.tickRoot() == BT::NodeStatus::RUNNING) {
        // Attente active
    }
```

But in my case the header does not exist. I guess this is [bt_zmq_publisher.h](https://github.com/BehaviorTree/BehaviorTree.CPP/blob/v3.8/include/behaviortree_cpp_v3/loggers/bt_zmq_publisher.h) but what I have to do ?

**Comment by facontidavide** [comment]
You guessed right. You should use the ZMQ publisher.

Note that **Groot 1 is discontinued** and the only reason why I am maintaining branch **3.8** is because of Nav2.

I will soon add compatibility between BT.CPP 3.8 and Groot 2. Once that is done, I will mention how connect the two

**Comment by Lecrapouille** [comment]
Thank you ! Sorry to disturb you with a noob question: I'm lost with all these versions. What should I do to play with BT.cpp while monitoring states (for debugging) ? Shall I compile and install the BT.cpp master branch (v 4.3.0) and download the Groot2 installer and pay a PRO license ? No other alternative, right ?

**Comment by facontidavide** [comment]
First, unless you are obliged for SOME reason to use 3.8, you should not.
Always use the latest version (4.3, at the time of writing).

Groot2 has some free features, for example a real-time monitor similar to Groot1.

But it has also some advanced features that require the PRO license (that is free for research and academia).

If you use this commercially, you should contact me to purchase a license dfaconti@auryntobotics.com
